sudo: required
language: go

go:
  - 1.11.x

services:
  - docker

addons:
  apt:
    packages:
      - docker-ce

install:
  - echo "Please don't go get"

script:
  - make test
  - make verify-codegen
  - TAG=${TRAVIS_TAG:-latest} make build

after_success:
  - if [ ! -s "$TRAVIS_TAG" ] ; then
      TAG=${TRAVIS_TAG} make push manifest
    fi
